### ISSUE TITLE
08/11/2022 - 08/11/2022 3.6.2 Update WBS

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#100]
Overview of WBS 
Updated on 24/11/2022

![Image](https://user-images.githubusercontent.com/90232201/203765566-b37cf031-8459-4456-9fc0-4e8d1f61ce05.png)

**Comment by 2102596sit** [comment]
Focused view of WBS
Updated on 24/11/2022

M1 WBS
![Image](https://user-images.githubusercontent.com/90232201/203765898-9916f896-6de9-47b3-b037-14aa7c031471.png)

M2 WBS


![Image](https://user-images.githubusercontent.com/90232201/203766166-0741ebc2-6e06-4efa-a0dc-868272d290cf.png)

M3 WBS


![Image](https://user-images.githubusercontent.com/90232201/203766275-c588cc81-f180-4c81-91a2-e5400f86fdc0.png)

**Comment by ShaneLimJiXuan** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
