### ISSUE TITLE
08/11/2022 - 08/11/2022 3.1.1 Correction: Update Class Diagram

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#101]
Start Date: 08/11/2022
Expected Completion date: 08/11/2022

**Comment by afifazfar07** [comment]
Updated class diagram
Completed as of 08/11/2022

![Image](https://user-images.githubusercontent.com/9715307/203767623-5a91f999-1295-4f04-98ec-916b8ce6e74f.png)

**Comment by ShaneLimJiXuan** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
