### ISSUE TITLE
09/11/2022 - 09/11/2022 3.1.2 Correction: Update Component Diagram

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#102]
Start date: 09/11/2022
Expected Completion date: 09/11/2022

**Comment by afifazfar07** [comment]
Updated Component Diagram
Completed as of 09/11/2022

![Image](https://user-images.githubusercontent.com/9715307/203768170-69d7d96b-601c-48e2-a76f-fc294f7790f9.png)

**Comment by ShaneLimJiXuan** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
