### ISSUE TITLE
10/11/2022 - 10/11/2022 3.1.3 Correction: Update Sequence Diagram

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#103]
Start date: 10/11/2022
Expected Completion date: 10/11/2022

**Comment by afifazfar07** [comment]
Updated Sequence Diagrams
Completed as of 10/11/2022



![Image](https://user-images.githubusercontent.com/9715307/203769157-a571ee1f-1778-4ac5-9ee7-ae20d2ccbb71.png)



![Image](https://user-images.githubusercontent.com/9715307/203769172-2addf80a-4080-404f-9338-61ba39bd1436.png)



![Image](https://user-images.githubusercontent.com/9715307/203769194-bc910c7d-bda4-40cc-af83-ea91754a36dc.png)



![Image](https://user-images.githubusercontent.com/9715307/203769211-fc810c77-6cf0-4306-b03d-b9cf96e81e61.png)



![Image](https://user-images.githubusercontent.com/9715307/203769229-d4cc7807-5032-41d2-9386-afef91b2c34d.png)



![Image](https://user-images.githubusercontent.com/9715307/203769242-6e1575da-274e-4c83-b93a-e972ca45a5fb.png)



![Image](https://user-images.githubusercontent.com/9715307/203769269-cd84b1bb-73ca-4a25-b6e0-39d8b70286dc.png)



![Image](https://user-images.githubusercontent.com/9715307/203769296-a43ed2eb-588b-44e3-938f-fd0122e573e1.png)



![Image](https://user-images.githubusercontent.com/9715307/203769315-e22feb6c-c8da-4417-a65f-0971bd70cb8e.png)

**Comment by ShaneLimJiXuan** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
