### ISSUE TITLE
24/11/2022 - 25/11/2022 3.5 Prototype Video

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#104]
Start date: 24/11/2022
Expected Completion date: 25/11/2022

Completed date: 25/11/2022

https://www.youtube.com/watch?v=9EFdtyChiWs&ab_channel=limshane

**Comment by 2102596sit** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
