### ISSUE TITLE
13/09/2022 - 21/09/2022 1.5 Use Case Description

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#23]
Use Cases completed as of 11 Sept:
-Create user account
-Assign job to staff

**Comment by S0meDev99** [comment]
Use cases Completed as of 13 Sept
-Create user account
-Assign job to staff

Use Cases completed as of 18 Sept
-Staff indicate job preference
-Staff add their availabilities

Use Cases completed as of 21 Sept:
-Staff edit their availabilities
-Staff reject job assignment

Refer to document to view

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by 2102596sit** [comment]
Completed as of 7/10/2022. Amendments after M1 report review.



![Image](https://user-images.githubusercontent.com/90232201/194579475-93e7e87e-4cbb-4400-9477-6a886fb306e6.png)



![Image](https://user-images.githubusercontent.com/90232201/194579575-7b097589-9e8e-41ee-b98e-814845ebc0d0.png)

**Comment by S0meDev99** [comment]
Updated use case descriptions seems to cover the updated use case diagram. Looks good to me.

**Comment by ShaneLimJiXuan** [comment]
Looks good to me!
