### ISSUE TITLE
05/09/2022 - 06/09/2022 1.2.2.1.1 High Fidelity Prototype - Crew Landing Page

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#25]
Completed as of 6th September 2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/191277233-a80f554d-2413-4491-831a-c2675f64e194.png)

(Updated as of 5th September 2022)

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
