### ISSUE TITLE
07/09/2022 - 08/09/2022 1.2.2.2.1 High Fidelity Prototype - Manager Landing Page

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#26]
Completed as of 8th September 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/191277143-49542869-da5e-43bb-8f40-321c8dcf9c6b.png)

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
