### ISSUE TITLE
08/09/2022 - 09/09/2022 1.2.2.1.3 High Fidelity Prototype - Crew Add Availability

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#27]
Completed as of 9th September 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/191277224-1dd244e6-f028-415d-83d2-1085820a8f05.png)
![Image](https://user-images.githubusercontent.com/33240428/191277218-987b7308-1a56-47ba-b830-7cd51026ea3d.png)
![Image](https://user-images.githubusercontent.com/33240428/191277221-0db757c8-8c96-4168-8d4a-131a85d117bf.png)
![Image](https://user-images.githubusercontent.com/33240428/191277222-38848d49-0341-4fcb-998c-0e8630b3708b.png)
![Image](https://user-images.githubusercontent.com/33240428/191277220-3b2f9e77-7ed0-43c6-95b6-ff167bb444e1.png)
![Image](https://user-images.githubusercontent.com/33240428/191277223-6b64289c-7dc6-465a-8389-84fa342424ec.png)
![Image](https://user-images.githubusercontent.com/33240428/191277219-7ebbafdc-e23a-433d-9169-f79dfd514c6e.png)

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
