### ISSUE TITLE
11/09/2022 - 12/09/2022 1.2.2.1.4 High Fidelity Prototype - Crew Edit Availability

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#28]
Completed as of 12th September 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/191278013-dc853d98-7b6f-4080-9273-1c97a8b98d31.png)

Updated as of 12th September 2022

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
LGTM too! I think we can settle with this. Good job guys!
