### ISSUE TITLE
06/09/2022 - 07/09/2022 1.2.2.1.2 High Fidelity Prototype - Crew Reject Assignment

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#29]
Completed as of 7th September 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/191277045-39cc6526-74fc-451c-9791-e609cfbdecb8.png)
![Image](https://user-images.githubusercontent.com/33240428/191277044-c7d6d2a8-9825-4a7b-a5b2-3cc541da03f4.png)
![Image](https://user-images.githubusercontent.com/33240428/191277047-121bd0f2-247c-4183-a3a6-8aed50520425.png)
![Image](https://user-images.githubusercontent.com/33240428/191277046-bafb135e-e0ed-4930-8d12-f3966ea66682.png)

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
