### ISSUE TITLE
13/09/2022 - 13/09/2022 1.1.3.1 Meeting Minutes

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#33]
Completed as of 13 September 2022

**Comment by afifazfar07** [comment]
Methodology
The client was asked to review high fidelity prototype design and provide feedback on what 
could be improved with the prototype.

(Updated as of 13th September 2022)

**Comment by afifazfar07** [comment]
Action Items (What things to change/improve)

1. Fixing color consistency for UI/UX, when crew is selected on job page, change selection color to grey from green. / @ShaneLimJiXuan  / 29/09/2022 
2.  Manager’s planner page should display weekly view instead of monthly view. / @2102596sit  / 29/09/2022 
3.  When allocating job assignments: 
a.  All available crew staff should be shown for selection, except staff that have over 40 work hours of workload allocated for the week. / @ShaneLimJiXuan  / 29/09/2022 
b.  All crew staff shown for selection will be sorted from the lowest workload hours allocated to the highest. / @afifazfar07  / 29/09/2022 
c.  All crew staff shown for selection will have their hours for their allocated workload displayed as a Quality-of-Life improvement. / @afifazfar07  / 29/09/2022 
4.  Staff job preference is reviewed by the manager every week, staff can make amends for job preference from the window period, Thursday to Friday, 2359. / @ShaneLimJiXuan  / 29/09/2022

**Comment by afifazfar07** [comment]
Other Notes  
 
Our client clarified information regarding his company’s day-to-day operations and policies: 
- Ferry operations are 24/7. 
- There are approximately 40 people working in the company.  

 
Our client agreed to proposed functions based on high fidelity prototype: 
- Most of the proposed functions based on high fidelity prototype meets client requirements, only items in actions items must be followed up.

(Updated as of 13th September 2022)

**Comment by ShaneLimJiXuan** [comment]
Good job team!

**Comment by 2102596sit** [comment]
Good job team!
