### ISSUE TITLE
20/09/2022 - 21/09/2022 1.3.5 Individual Member Task Reflections

### ISSUE THREAD

**Issue by S0meDev99** [afifazfar07/ict2201-p1-8#34]

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/194553493-5b7b9a9f-4707-4c74-a75a-5c06f9e6fef6.png)

completed as of 21/09/2022

Check each other work

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good!

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
