### ISSUE TITLE
16/09/2022 - 18/09/2022 1.3.4.1 Software Estimation

### ISSUE THREAD

**Issue by S0meDev99** [afifazfar07/ict2201-p1-8#35]
Completed as of 18th September

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/191521243-74c9c132-30eb-4b9f-89d1-472f915277a4.png)

**Comment by 2102596sit** [comment]
This needs to rectify after our m1 report review.

**Comment by S0meDev99** [comment]
Re-opening this issue to update the Cost Estimation.

**Comment by S0meDev99** [comment]
6/10/2022 - 7/10/2022 - Correction: 4.1 Software Estimation must match with what was described in Use Case Diagram

![Image](https://user-images.githubusercontent.com/90775954/194616742-0f139738-88c2-407a-9772-d600cfab8532.png)



![Image](https://user-images.githubusercontent.com/90775954/194616752-1172e503-0964-4d23-8dfe-72bbfc93f2ef.png)

**Comment by S0meDev99** [comment]
6/10/2022 - 7/10/2022 - Correction: 4.1 Software Estimation estimated effort in developer-hours must be changed to a range

![Image](https://user-images.githubusercontent.com/90775954/194617190-0e1bdc1f-a2e5-46e6-8b9e-abe29c4d3265.png)

**Comment by 2102596sit** [comment]
It looks good now.
