### ISSUE TITLE
09/09/2022 - 18/09/2022 1.3.4.2.1 Work Breakdown Structure

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#41]

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/194554634-cc218bca-0fd2-4276-b159-0bd2df04af1e.png)

completed as of 18/09/2022

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
