### ISSUE TITLE
13/09/2022 - 21/09/2022 1.3.4.2.2 Gantt Chart

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#42]

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/194554187-e1eb4cff-b3e7-414d-a96a-e4cd036ceeaf.png)

Completed as of 21/09/2022

**Comment by 2102596sit** [comment]
Looks good to me. What do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!
