### ISSUE TITLE
01/09/2022 - 03/09/2022 1.3.1.1 Product Scope

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#43]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194614991-0b9d59cc-d3bb-4dea-9275-2fd67571aad8.png)

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
