### ISSUE TITLE
03/09/2022 -05/09/2022 1.3.1.2 Related Background Literature

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#44]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194614122-6e83f86b-33e8-4ba7-b33e-614af3034d05.png)

Completed As of 05/09/2022

**Comment by ShaneLimJiXuan** [comment]
Looks correct! Great job!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
