### ISSUE TITLE
01/09/2022 - 03/09/2022 1.3.1.3 Intended Audience and Document Review

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#45]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194614909-39d750ef-b24c-4b70-9d53-f2e69517b361.png)

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
