### ISSUE TITLE
05/09/2022 -06/09/2022 1.3.2.1 Product Overview

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#47]

**Comment by 2102596sit** [comment]
Product Overview 

The intended usage for the users is for them to log in to the web application via either the office computers or their mobile phones. The users can only access the web application in the company’s internal network. The web application system will communicate with the database to verify their credentials. When logged in, the users can interact with the web application to perform actions, such as job allocation and user creation, depending on their user’s role.

**Comment by S0meDev99** [comment]
6/10/2022 - 7/10/2022 - Corrected system architecture diagram in 2.1 Product Overview



![Image](https://user-images.githubusercontent.com/90775954/194617641-c41f24e2-569d-4d3b-a31c-56331efc41be.png)

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
