### ISSUE TITLE
05/09/2022 - 06/09/2022 1.3.2.2 Product Functionality

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#48]

**Comment by 2102596sit** [comment]
Product Functionality 

PF1: System shall allow manager to be able to visualise the all-staff workload on the landing page. 

PF2: System shall allow managers to allocate jobs to crew staff for one week at a time. 

PF3: System shall allow manager to be able to view up to three staff availability on the job allocation page. 

PF4: System shall allow staff to add their availabilities. 

PF5: System shall allow staff to edit their availabilities. 

PF6: System shall allow staff to reject their job assignments

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
