### ISSUE TITLE
05/09/2022 - 07/09/2022 1.3.2.3 Assumptions and Dependencies

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#49]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194613938-a5773ad3-2ed9-4db8-9d90-4ce21ae77cfb.png)

Complete As of 07/09/2022

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
