### ISSUE TITLE
07/09/2022 - 09/09/2022 1.3.3.1 User Interface Requirements

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#50]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194613739-d42a1b6e-b4e4-48c5-abe1-1bfda180145b.png)

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
