### ISSUE TITLE
07/09/2022 - 09/09/2022 1.3.3.2 Functional Requirements

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#51]

**Comment by 2102596sit** [comment]
Functional Requirements 

Admin  

FR1: Admin shall be able to add a new manager to the web application system.  

FR2: Admin shall be able to add new staff, either ferry captain or ferry crew, to the web application system.  

FR3: System shall send an e-mail when adding new users to the web application system.  

    

Manager  

FR4: Manager shall be able to allocate staff jobs up to 1 week in advance.  

FR5: Manager shall be able to view the workload allocated to all staff.  

FR6: Manager shall be able to view individual staff preferences.  

FR7: Manager shall be able to view individual staff’s availability.  

FR8: System shall send an e-mail when staff has been allocated a job.  

FR9:  The manager allocation system shall not display staff over 40 hours.  

FR10:  The manager allocation system shall display staff in ascending order based on hours allocated for the week.  

FR11:  The manager allocation system shall not display staffs who are not at the selected location where the manager is currently planning.  

FR12:  The manager allocation system shall not display staffs who have allocation at the selected time where the manager is currently planning.  

   

Staff   

FR13: Staff shall be able to indicate their job preference for each week  

FR14: Staff shall be able to reject jobs assigned to them.  

FR15: System shall send an e-mail when staff has selected and submitted a job preference. 

FR16: System shall send an e-mail when staff has rejected a job allocation.  

FR17: Staff shall be able to view job allocation a week in advance.  

FR18: Staff shall be able to view the total hours worked for the week.  

   

System   

FR19: System shall visualize the staff’s workload in a form of a weekly calendar on the staff’s landing page.   

FR20: System shall visualize all staff’s workload in a form of a weekly calendar on the manager’s landing page.  

FR21:  The system shall prompt the staff to discuss the jobs with their manager before proceeding with an allocated job rejection.

**Comment by S0meDev99** [comment]
6/10/2022 - 7/10/2022 -Correction: Shift NFR1 to NFR9 from 3.4 to Functional Requirements

**Comment by S0meDev99** [comment]
Looks good to me! Good job @2102596sit

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
