### ISSUE TITLE
09/11/2022 - 11/09/2022 1.3.3.3 Non-functional Requirements

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#52]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194614417-530b7f58-2d1b-4c20-9b32-cd5948ccc224.png)

**Comment by S0meDev99** [comment]
6/10/2022 - 7/10/2022 - Correction: Shift UIR1 to UIR2 from 3.1 to Non-functional Requirement, and UIR3 to UIR4 from 3.1 to Functional Requirement

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
