### ISSUE TITLE
07/09/2022 - 11/09/2022 1.3.3.3.1 Performance Requirements

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#53]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194614307-2edc5bdd-f88f-4285-8833-9afd0b4f39ad.png)

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
