### ISSUE TITLE
16/10/2022 - 17/10/2022 2.2 Architecture Design

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#54]

**Comment by 2102596sit** [comment]
Started on 24/9/2022

1. Encapsulating classes into components
2. Coming up with the first iteration components diagram.

Completed as of 2/10/2022
1. Revising components diagram.

**Comment by afifazfar07** [comment]
Started Client-Server architecture and Entity Control Boundary on 16/10/2022, delayed due to correction priority

New expected time of completions:
Client-Server architecture: 16/10/2022 - 17/10/2022
Entity Control Boundary: 16/10/2022 - 17/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/33240428/198812439-0ff63eab-c661-4a1b-be24-52e692c582b3.png)



Client-Server architecture done as of 17/10/2022

**Comment by afifazfar07** [comment]
Let me know what you all think!

**Comment by 2102596sit** [comment]
The revision looks good to me.

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Architecture design is accurate. Good job, guys! I'll close this thread as it is completed.
