### ISSUE TITLE
10/10/2022 - 16/10/2022 2.3 Detailed Design of Class Diagram

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#55]

**Comment by 2102596sit** [comment]
Start on 2/10/2022

 1. Describe concepts of a ferry job allocation system for your development team + requirements in a paragraph.
 2. Identifying Services & Behaviours for candidate classes.
 3. First Iteration of Class Diagram

5/10/2022
 
1. Second Iteration of Class Diagram

Completed as of 9/10/2022

1. Refining the Second iteration of the class diagram

**Comment by ShaneLimJiXuan** [comment]
Start on noun analysis 10/10/2022, Delayed due to correction priority. 

New expected time of completions

Noun analysis, 10/10/2022 - 11/10/2022

Initial Class Diagram - Class Diagram, 11/10/2022 - 13/10/2022

Refined Class Diagram - Class Diagram, 13/10/2022 - 15/10/2022

Software Design Pattern, 15/10/2022 - 16/10/2022

**Comment by ShaneLimJiXuan** [comment]
Noun analysis completed on 11/10/2022


![Image](https://user-images.githubusercontent.com/33240428/196752146-01f82f3c-db4b-4573-8894-ae13e2817b01.png)

**Comment by ShaneLimJiXuan** [comment]
Initial Class Diagram - Class Diagram completed on 13/10/2022



![Image](https://user-images.githubusercontent.com/33240428/197337395-f354436d-cd32-49ca-a91d-216e6f5c86f4.png)

**Comment by ShaneLimJiXuan** [comment]
Refined Class Diagram - Class Diagram completed as of 15/10/2022






![Image](https://user-images.githubusercontent.com/33240428/197402754-4aa00e26-d3ed-4ac6-8605-f03c6813c44f.png)

**Comment by ShaneLimJiXuan** [comment]
Software Design Pattern completed 16/10/2022

![Image](https://user-images.githubusercontent.com/33240428/196754340-6542bc30-7077-4ff7-b98e-50a2495420c3.png)

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Diagrams looks nice, it makes sense. Thanks for the hard work, guys! I'll close this thread as it is completed.
