### ISSUE TITLE
18/10/2022 - 25/10/2022 2.4 Sequence Diagram

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#56]
Numbering revised to 2.4 on WBS.

**Comment by 2102596sit** [comment]
Started on 18/10/2022
Started on sequence diagrams for UC-1, UC-2, UC-3, UC-4

21/10/2022(Gantt chart projection for completion)
Started on sequence diagrams for UC-5, UC-6, UC-7, UC-8, UC-9

Sequence diagram completed on 25/10/2022
Added description for UC-1 TO UC-9.

**Comment by ShaneLimJiXuan** [comment]
20/10/2022
Completed Sequence diagram for UC 1 to UC 4. Delayed due to corrections priority

New projected completion date is 25/10/2022

UC-1, Create Account

![Image](https://user-images.githubusercontent.com/33240428/197349879-d15bcd86-2cd7-4a8e-ac25-dd41efb2530a.png)

UC - 2, Assign Job

![Image](https://user-images.githubusercontent.com/33240428/197349888-fd5ee71f-ca3c-4e04-81c1-16119f060305.png)

UC - 3, Add Schedule

![Image](https://user-images.githubusercontent.com/33240428/197349915-94073794-081c-4729-a060-12453d2b714c.png)

UC - 4, Edit Schedule

![Image](https://user-images.githubusercontent.com/33240428/197349922-ca4c9b10-fd66-42f0-8237-d67ef291e5d5.png)

Please review the sequence diagrams and inform if there is any issues.

**Comment by ShaneLimJiXuan** [comment]
21/10/2022

Sequence Diagrams for UC5 to UC 9 is currently WIP.  On track to be completed by 25/10/2022.

**Comment by ShaneLimJiXuan** [comment]
Descriptions of UC1 to UC4 sequence diagram can be found within the M2 report. Please let me know what you guys think about it.

**Comment by 2102596sit** [comment]
The diagrams for UC1 to UC4 look good to me.

**Comment by afifazfar07** [comment]
Looks good to me as well!

**Comment by S0meDev99** [comment]
Sequence diagrams has the correct format and information. Lets continue the good work for UC5 to UC9!

**Comment by afifazfar07** [comment]
UC-5 Remove Schedule Preference


![Image](https://user-images.githubusercontent.com/9715307/198298810-2c06c0f2-8e0d-4976-8935-27a52eb65a6f.png)


UC-6 Reject Job Assignment


![Image](https://user-images.githubusercontent.com/9715307/198299016-790153ad-491c-4937-a7a0-d0192bc5c8d6.png)


UC-7 Change Account Password


![Image](https://user-images.githubusercontent.com/9715307/198299203-2a22a190-079b-42ec-9826-ba3f72a5aa32.png)


UC-8 Delete Account


![Image](https://user-images.githubusercontent.com/9715307/198299280-0e8c4f2f-0695-4e3c-ab62-7ef80909f135.png)


UC-9 Edit Job to Allocated Staff


![Image](https://user-images.githubusercontent.com/9715307/198299393-5412bbc9-e329-4288-8cdd-9aabf0af96d6.png)


Please review the sequence diagrams and inform if there are any issues

**Comment by ShaneLimJiXuan** [comment]
Looks great to me

**Comment by 2102596sit** [comment]
Looks great to me. what do you guys think?

**Comment by S0meDev99** [comment]
The diagrams look great! Thanks for the hard work guys. I shall close this issue.
