### ISSUE TITLE
10/09/2022 - 11/09/2022 1.3.3.3.2 Safety and Security Requirements

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#58]

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194614232-225a07e9-f994-47d8-b11e-db5f26b5a57f.png)

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I'll close this thread as it is completed.
