### ISSUE TITLE
20/11/2022 - 25/11/2022 3.4 Figma Prototype

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#59]
Start date: 20/11/2022
Expected Completion date: 25/11/2022

Completed date: 25/11/2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/201729757-62aa20e1-7fbe-4ac1-b0f0-b22d5c650bfd.png)

created the manager home page and the planner page!

**Comment by 2102596sit** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by ShaneLimJiXuan** [comment]
[Prototype!](https://www.figma.com/proto/BZWMR7Ym7rCbssJKO8VO4o/2201-Prototype?node-id=199%3A5712&scaling=contain&page-id=0%3A1&starting-point-node-id=199%3A5712&show-proto-sidebar=1)

PROTOTYPE COMPLETED! Refer to link

Staff/Manager Flow 1
Admin Flow 2

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me !

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
