### ISSUE TITLE
02/09/2022 - 02/09/2022 1.1.2 Draft questions for clients

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#6]
Completed as of 12th September 2022

**Comment by afifazfar07** [comment]
Questions to ask:
1. Schedule for each trip. How long, what time?
2. What are the working shifts for crew/capt?
3. ask feedback on UI/UX based on paper prototype?
4. For login, do we need any authentication and password recovery? 

(Updated as of 2nd September 2022)

**Comment by afifazfar07** [comment]
Updated Questions to ask:

1. Show - Prototype (3mins)
2. Confirmation of schedule (crew shifts and routing timing) if wrong give email
3. Feed back on UI/UX on prototype
4. Show availability and preference (default all available, use website to show preference / reject job) *
-5 weeks of availability
-indicate job preference for the week
5. Access of website (own device / terminals located at place of work)
- if own device, login confirmation, how many attempts b4 locking account
6. Initial requirement of "The manager should be able to allocate jobs to staff for one week at a time" being the manager should be able to allocate jobs to staff up to 1 week in advance or have to be done 1 week at a time?
7. Max expected loading time for webpage
8. Any additional questions

(Updated as of 12th September 2022)

**Comment by ShaneLimJiXuan** [comment]
Good job team! we managed to clarify requirements from the client

**Comment by 2102596sit** [comment]
Looks good to me
