### ISSUE TITLE
4/10/2022 - 4/10/2022 - 2.1.1.2 Correction: Requirements elicitation method created as new Section 1.4: Requirement Elicitation Method

### ISSUE THREAD

**Issue by 2102596sit** [afifazfar07/ict2201-p1-8#67]
Start date: 4/10/2022
Estimated completion date: 4/10/2022

Completed date: 4/10/2022

![Image](https://user-images.githubusercontent.com/90232201/194577778-00c81e8d-cbd9-4499-8965-fc7e680d90aa.png)

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me
