### ISSUE TITLE
01/09/2022 - 02/09/2022 1.1.1 Analyze Project Description

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#7]
Completed as of 4th September 2022

**Comment by afifazfar07** [comment]
rough summary of project description

online workload management system

overview of manpower
provide interactive and visual way

employee can:
-see job assignments
-see working hours engaged/assigned
-inform the system of their availabilities, up to one month earlier
-indicate jobs they cannot fulfil ahead of time

manager can:
-visualise manpower availability, up to one month earlier
-visualise job assignment
-allocate job
-visualise individual employee workload and availabilities

(Written as of 2nd September 2022)

**Comment by afifazfar07** [comment]
ferry cabin crew division:
-work allocation assigned every monday
-work allocation planning every thursday
-all employee availabilities informed by every wednesday
-employee miss weekly deadline, request dealt case-by-case

-weekly roster dependent on ferry route
-fleet consist of 26 ferries
-currently operating 4 routes
-each and every route, min. 1 capt and 2 crew
-staff do not need to travel between routes
-ferry not stationery for more than 2 hours, maximise profits

captain:
-licensed mariner
-overall command and control of:
• navigation
• manoeuvring
• stowage
• communications
• safe handling of ship

crew:
-serve passengers
-keep ferry clean and tidy
-assist captain:
• stowage
• safe handling of ship

route:
• HarbourFront Centre, Singapore and Batam Centre, Indonesia (8 times a day bidirectional)
• HarbourFront Centre, Singapore and Sekupang, Indonesia (3 times a day bidirectional)
• HarbourFront Centre, Singapore and Tanah Merah, Singapore (every 2 hours)
• Tanah Merah, Singapore and Bandar Bintan, Indonesia (4 times a day bidirectional)

(Written as of 2nd September 2022)

**Comment by afifazfar07** [comment]
project is web application

manager abilities:
-visualise staff workload on landing page
• show top 3 employee with lowest workload 
• highlight employees with over 40 hour jobs allocated
-allocate job to employee, for one week at a time
-view up to 3 employee availability and relevant information to make job assignment easier

employee abilities:
-view:
• weekly job assignments
• overall workload for the month
-add and edit availabilities, up to 5 weeks ahead
-indicate job preference for the week
-reject jobs assigned to them
• will be warned to discuss job with manager before proceeding with rejection

admin abilities:
-add new staff and manager to system

(Written as of 4th September 2022)

**Comment by afifazfar07** [comment]
Tasks

1. Web application
2. Landing page = Time slot allocation page
3. Allocate the following weeks
4. View up to 3 staff availbality and relavent info at a time on job allocation page
5. Staff avalibility = Show workload assigned, staff’s job preference, staff’s
location at a particular date
6. Landing page show top 3 staff with the lowest workload + highlight over 40hrs
7. Staff can view weekly assignment and overall work load for the month (reset a month)
8. Staff can edit their availability 5 week ahead of time
9. Staff can indicate preference for the week
10. Staff can reject assignment (need to discuess with manager b4 rejecting, have prompt to ask if they have discuess with manager)
11. IT Admin over sea staff and managers to the system

(Written as of 4th September 2022)

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by S0meDev99** [comment]
LGTM!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
I think we can settle with this. Good job guys!

**Comment by 2102596sit** [comment]
Looks good to me
