### ISSUE TITLE
9/10/2022 - 9/10/2022 - 2.1.4.3 Correction: Added software development life cycle

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#74]
Start date: 9/10/2022
Estimated completion date: 9/10/2022

Completed date: 9/10/2022

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/33240428/196745083-526eff32-94e0-4ce2-8ac1-9eb5db56ad1a.png)



Completed as of 9/10/2022

**Comment by ShaneLimJiXuan** [comment]
Looks good!

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me
