### ISSUE TITLE
Starfish Retrospective

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#75]
Created on 4th October 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/193757795-8974cac9-80ef-4338-a2db-5f44ca877efa.png)

**Comment by ShaneLimJiXuan** [comment]
any comments?

**Comment by 2102596sit** [comment]
Looks good to me! Good work everyone!

**Comment by S0meDev99** [comment]
Thanks for the discussion and feedbacks for one another for our progress for our M1 report.
