### ISSUE TITLE
13/09/2022 - 15/09/2022 1.3.4.2.3 Software Development Life Cycle

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#76]
Start date: 13/09/2022
Estimated completion date: 15/09/2022
Completed date: 15/09/2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/194571605-57933fd4-c80c-45a9-8e7e-8da12eea16bc.png)

Completed software development life cycle as of 15/09/2022

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
LGTM too! I think we can settle with this. Good job guys!

**Comment by 2102596sit** [comment]
It looks good now.
