### ISSUE TITLE
01/09/2022 - 20/09/2022 1.4 Use Case Diagram

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#8]
Completed as of 20th September 2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/191269915-8cf0feea-68e0-43b5-9b55-7bede089c99f.png)

Use Case Diagram updated with additional notes from Client Meeting
(Updated as of 20th September 2022)

**Comment by 2102596sit** [comment]
![Image](https://user-images.githubusercontent.com/90232201/194598688-f1a6d0c7-8b97-41f0-b6c3-20be13cf1d16.png)



Use Case Diagram updated After M1 meeting. As of 7/10/2022.

**Comment by ShaneLimJiXuan** [comment]
Look good to me!

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by S0meDev99** [comment]
LGTM too! I think we can settle with this. Good job guys!
