### ISSUE TITLE
Updated M1 Report as of 08/10/2022

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#80]

**Comment by ShaneLimJiXuan** [comment]
[ICT2x01_M1__p1-8.pdf](https://github.com/afifazfar07/ict2201-p1-8/files/9739486/ICT2x01_M1__p1-8.pdf)



Updated M1 report as of 08/10/2022.

**Comment by 2102596sit** [comment]
Looks good. We can add more stuff and improve on our M2 report as we go along.

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
I've read the updated M1 report, it looks good to me. I'll close this thread as it is completed.
