### ISSUE TITLE
14/10/2022 Use Case Description Update

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#81]
Completed as of 14th October 2022

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<div class="OutlineElement Ltr SCXW52561963 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TableContainer Ltr SCXW52561963 BCX0" style="margin: 2px 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; position: relative; display: flex; justify-content: flex-start;">

Use Case ID: | UC-1 | Number of transactions: 4
-- | -- | --
Use Case Name: | Create account
Description: | Create user account for Manager and Staff.
Primary Actor: | Administrator
Preconditions: | User information such as names and roles in organisation.
Postconditions: | Main: User is created. System updates the Database. 2a. If the same username already exists in the Database, user not created. E-mail sent. 6a. E-mail was not sent.
Main Success Scenarios: | Administrator input username, e-mail address, phone number, gender, home address, the role of manager, ferry captain or crewmate. Administrator submits input. System prompts Administrator to confirm his/her input. Administrator accepts confirmation. System generates and set randomized passwords for the users. System registers new user successfully in Database. System display that a new user has been created. System send e-mail with system generated password with username to new user.
Alternative Scenarios: | 2a. Username already exist. 2a1. System prompts the administrator to enter new username.
Priority | Medium

</div></div>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-2 | Number of transactions: 4
-- | -- | --
Use Case Name: | Assign job to staff
Description: | Assign job based on manpower availability and staff preference to staff.
Primary Actor: | Manager
Preconditions: | Manager is logged in. Job must be available. Staff must be registered in Database.
Postconditions: | Main: Confirmation e-mail sent. System updates in the Database.
Main Success Scenarios: | Manager selects date for route, timeslot and date. Manager submits input. System prompts Manager to confirm his/her input. Manager accepts confirmation. System updates the Database. System displays updated planning page. Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 5a. System fails to update Database. 5a1. System gives a message “Update Fail, Try Aagin" 5a2. Staff can choose to retry or quit screen.
Priority | High


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-3 | Number of transactions: 3
-- | -- | --
Use Case Name: | Add preference
Description: | Staff can add their job preference one week before allocation.
Primary Actor: | Staff
Preconditions: | Staff is logged in. Staff must be registered in Database.
Postconditions: | Main: Confirmation e-mail is sent to the staff. System updates in the Database.
Main Success Scenarios: | Staff selects date, route and time. Staff presses save. System updates Database. System display updated current preference for the week. Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 3a. System fails to update Database. 3a1. System gives a message “Update Fail, Try Aagin 3a2. Staff can choose to retry or quit screen.
Priority | High


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-4 | Number of transactions: 5
-- | -- | --
Use Case Name: | Edits preference
Description: | Staff can edit their job preference one week before allocation.
Primary Actor: | Staff
Preconditions: | Staff is logged in. Staff must be registered in Database. Existing preferences were made.
Postconditions: | Main: Confirmation e-mail is sent to the staff. System updates in the Database.
Main Success Scenarios: | Staff select date with existing preference. System displays existing preference. Staff presses edit button. System display list of all available route and time for selected date. Staff selects route and time for selected date. Staff presses save. System updates Database System display updated current preference for the week. Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 7a. System fails to update Database. 7a1. System gives a message “Update Fail, Try Aagin" 7a2. Staff can choose to retry or quit screen.
Priority | High


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-5 | Number of transactions: 4
-- | -- | --
Use Case Name: | Removes preference
Description: | Staff can remove preference one week before allocation
Primary Actor: | Staff
Preconditions: | Staff is logged in. Staff must be registered in Database. Existing preferences were made.
Postconditions: | Main: Confirmation e-mail is sent to the staff. System updates in the Database.
Main Success Scenarios: | Staff select date with existing preference. System displays existing preference. Staff selects route and time for removal. Staff presses remove System updates Database System display updated current preference for the week. Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 5a. System fails to update Database. 5a1. System gives a message “Update Fail, Try Aagin" 5a2. Staff can choose to retry or quit screen.
Priority | High


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-6 | Number of transactions: 5
-- | -- | --
Use Case Name: | Reject job assignment
Description: | Staff rejects the job assigned to them by the manager.
Primary Actor: | Staff
Preconditions: | Staff is logged in. Manager has assigned staff to a job. Staff discussed with manager about reason for rejecting.
Postconditions: | Main: Database system has been updated. E-mail confirmation sent.
Main Success Scenarios: | System display dates and jobs assigned to staff. Staff selects date to reject. System displays jobs for the date. Staff selects jobs to reject. Staff presses reject. Staff input reason for rejecting the job. Staff submits their input. System updates Database. System displays updated job assignment. Confirmation e-mail sent to Manager and Staff e-mail mailbox.
Alternative Scenarios: | 8a. System fails to update Database. 8a1. System gives a message “Update Fail, Try Aagin" 8a2. Staff can choose to retry or quit screen.
Priority | Medium


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-7 | Number of transactions: 5
-- | -- | --
Use Case Name: | Change account password
Description: | Staff change password for their account. Password is set to expire every 90 days.
Primary Actor: | Staff
Preconditions: | Staff knows current password. Staff password reaches password expiry date then system prompts for password change.
Postconditions: | Main: Confirmation e-mail sent.
Main Success Scenarios: | Staff goes to change password page. Staff input current ID and password. System validates entered password with Database-stored password. System prompts staff to enter new password. Staff input new password. System validates new password. System updates Database. System displays that password has been change. Confirmation e-mail sent to Staff e-mail mailbox.
Alternative Scenarios: | 3a. Entered password is incorrect. 3a1. Staff can choose to re-enter password or quit screen. 6a. New password same as old password. 6a1. System prompts user to enter another password.
Priority | Low


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC-8 | Number of transactions: 4
-- | -- | --
Use Case Name: | Delete account.
Description: | Delete user account for Manager and Staff.
Primary Actor: | Administrator
Preconditions: | User leaves organisation
Postconditions: | Main: User is deleted. System updates the Database.
Main Success Scenarios: | 1.  Administrator selects delete user 2.  Administrator input username 3.  Administrator submits input. 4.  System prompts Administrator to confirm his/her input. 5.  Administrator accepts confirmation. 7.  System removes user successfully from Database. 8.  System display that a user has been removed. 9.  System send e-mail notification that a user has been deleted to the administrator
Alternative Scenarios: | 2a. Username does not exist. 2a1. System prompts the administrator that the username does not exist.
Priority | Medium


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<div class="OutlineElement Ltr SCXW125651866 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TableContainer Ltr SCXW125651866 BCX0" style="margin: 2px 0px 2px -5px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; position: relative; display: flex; justify-content: flex-start;">

Use Case ID: | UC-9 | Number of transactions: 2
-- | -- | --
Use Case Name: | Validate overall workload for the month
Description: | Staff valid overall workload for the month if there are discrepancy report to manager
Primary Actor: | Staff
Preconditions: | Workload is updated to the end of month.
Postconditions: | Main: Number of hours is correct
Main Success Scenarios: | System display workload for the month Staff cross checks if workload amount is correct Number of hours is correct
Alternative Scenarios: | 3a. Number of hours is incorrect 3a1. Staff reports to manager to about discrepancy in work hours.
Priority | Low

</div></div><div class="OutlineElement Ltr SCXW125651866 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW125651866 BCX0" paraid="90784495" paraeid="{5c156c4e-c288-423b-bc5e-ec5b70b32d53}{40}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span data-contrast="auto" xml:lang="EN-CA" lang="EN-CA" class="TextRun SCXW125651866 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; font-size: 12pt; line-height: 20px; font-family: Times, Times_EmbeddedFont, &quot;Times New Roman&quot;, serif; font-weight: bold;"><span class="NormalTextRun SCXW125651866 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"></span></span><span class="EOP SCXW125651866 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 12pt; line-height: 20px; font-family: Times, Times_EmbeddedFont, &quot;Times New Roman&quot;, serif;"> </span></p></div>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>


Use Case ID: | UC10 | Number of transactions: 4
-- | -- | --
Use Case Name: | Edit Job Allocated to Staff
Description: | Edit existing job based on manpower availability and staff preference to staff.
Primary Actor: | Manager
Preconditions: | Manager is logged in. Job must be available. Staff must be registered in Database.
Postconditions: | Main: Confirmation e-mail sent. System updates in the Database.
Main Success Scenarios: | Manager selects pre-existing jobs allocation. Manager submits input. System prompts Manager to confirm his/her input. Manager accepts confirmation. System updates the Database. System displays updated planning page. Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 5a. System fails to update Database. 5a1. System gives a message “Update Fail, Try Again" 5a2. Staff can choose to retry or quit screen.
Priority | High


</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
What do you all think?

**Comment by 2102596sit** [comment]
Great work, it looks good to me.

**Comment by afifazfar07** [comment]
Looks good, thanks!

**Comment by S0meDev99** [comment]
Updated Use Case Descriptions looks good to me. I'll close this thread as it is completed.
