### ISSUE TITLE
14/10/2022 Use Case Diagram Update

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#82]
Completed as of 14th October 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/195661709-7aa345de-d771-423c-ba46-94b1465d927f.png)

**Comment by ShaneLimJiXuan** [comment]
Guys what ya think?

**Comment by 2102596sit** [comment]
It looks good.

**Comment by afifazfar07** [comment]
Looks good, thanks!

**Comment by S0meDev99** [comment]
Updated diagram looks good to me. I'll close this thread as it is completed.
