### ISSUE TITLE
14/10/2022 Cost Estimation Update

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#83]
Completed as of 14th October 2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/195662466-e136f095-558a-40f9-ab8e-a84f1d5d47bf.png)

**Comment by afifazfar07** [comment]
Looks good, thanks!

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Corrected software estimation looks good to me. I'll close this thread as it is completed.
