### ISSUE TITLE
4/10/2022 - 4/10/2022 - 2.1.1.1 Correction: Research about shipping industry operations added to Section 1.2: Related Background Literature

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#85]
Start date: 4/10/2022
Estimated completion date: 4/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196741692-5d895ee9-717f-4db4-bc09-11485867854d.png)


Completed date: 4/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
