### ISSUE TITLE
5/10/2022 - 5/10/2022 - 2.1.2.1 Correction: Added paragraph explaining what is to be covered inside the Overall Description

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#86]
Start date: 5/10/2022
Estimated completion date: 5/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196742901-ad498de8-829a-4db6-95da-028e0f831fa5.png)

Completed date: 5/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
