### ISSUE TITLE
5/10/2022 - 5/10/2022 - 2.1.2.2 Correction: Created new System Architecture Diagram to better represent the system

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#87]
Start date: 5/10/2022
Estimated completion date: 5/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196743808-7fa01d53-e9aa-4e85-b246-95f1b204bdbc.png)


Completed date: 5/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Looks good to me. I'll close this thread as it is completed.
