### ISSUE TITLE
6/10/2022 - 6/10/2022 - 2.1.3.1 Correction: Added paragraph explaining what is to be covered inside the Specific Requirements

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#88]
Start date: 6/10/2022
Estimated completion date: 6/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196745011-b10b8f3e-68a7-412c-937f-1c85014175d8.png)

Completed date: 6/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Corrected info looks good to me. I'll close this thread as it is completed.
