### ISSUE TITLE
6/10/2022 - 6/10/2022 - 2.1.3.2 Correction: Inserted new User Interface Requirements and shifted previous UIR1 and UIR2 to non-functional requirements, and UIR3 and UIR4 to functional requirements

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#89]
Start date: 6/10/2022
Estimated completion date: 6/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196746263-99fe0349-24d4-4467-aa63-1b26e3ff4fbe.png)



![Image](https://user-images.githubusercontent.com/9715307/196746467-9084233c-9d62-4a88-bbc5-bb87e36873ab.png)



![Image](https://user-images.githubusercontent.com/9715307/196746616-9f9ad33e-eebb-4300-9569-518ec1092512.png)

Completed date: 6/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Corrected info looks good to me. I'll close this thread as it is completed.
