### ISSUE TITLE
6/10/2022 - 7/10/2022 - 2.1.3.3 Correction: Updated Use Case Model diagram

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#90]
Start date: 6/10/2022
Estimated completion date: 7/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196747109-21b96f23-f118-4327-be89-a5ce8755a752.png)

Completed date: 7/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Corrected diagram looks good to me. I'll close this thread as it is completed.
