### ISSUE TITLE
7/10/2022 - 7/10/2022 - 2.1.3.4 Correction: Shifted NFR1 to NFR9 from non-functional requirements to functional requirements

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#91]
Start date: 7/10/2022
Estimated completion date: 7/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196748160-dd29df40-038f-4920-a31c-bb419242ad6f.png)



![Image](https://user-images.githubusercontent.com/9715307/196747949-4c55009e-61a7-4ad7-9387-5dff0cec94b6.png)



![Image](https://user-images.githubusercontent.com/9715307/196748034-d04a5e90-3cdc-4a5f-badc-39568ed89b1c.png)

Completed date: 7/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Adjustments look good to me. I'll close this thread as it is completed.
