### ISSUE TITLE
8/10/2022 - 9/10/2022 - 2.1.4.1 Correction: Added missing Use Cases from updated Use Case Model diagram to represent all use cases

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#92]
Start date: 8/10/2022
Estimated completion date: 9/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196749172-2c19feec-04f1-4f99-9f28-914ab687b6e7.png)

Completed date: 9/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Corrected info looks good to me. I'll close this thread as it is completed.
