### ISSUE TITLE
8/10/2022 - 8/10/2022 - 2.1.4.2 Correction: Added estimated duration to complete project

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#93]
Start date: 8/10/2022
Esitmated completion date: 8/10/2022

**Comment by afifazfar07** [comment]
![Image](https://user-images.githubusercontent.com/9715307/196749712-aa3d24e4-001c-4047-8deb-577f12ea4d6f.png)

Completed date: 8/10/2022

**Comment by afifazfar07** [comment]
Looks good to me, what do you guys think?

**Comment by ShaneLimJiXuan** [comment]
Looks good to me too!

**Comment by 2102596sit** [comment]
This looks good to me.

**Comment by S0meDev99** [comment]
Corrected info looks good to me. I'll close this thread as it is completed.
