### ISSUE TITLE
02/10/2022 -02/10/2022 2.5.1 Update Work Breakdown Structure

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#95]
Start date: 02/10/2022
Estimated completion date: 02/10/2022

Completed date: 02/10/2022

**Comment by ShaneLimJiXuan** [comment]
![Image](https://user-images.githubusercontent.com/33240428/198298067-cdd066ea-761f-4383-977b-97f6e23f2229.png)


![Image](https://user-images.githubusercontent.com/33240428/198298628-03b636d4-9387-434c-ac32-f2b4b3a2a5df.png)


![Image](https://user-images.githubusercontent.com/33240428/198298172-72ccb415-7589-4df4-a281-efaf82897f63.png)


![Image](https://user-images.githubusercontent.com/33240428/198298697-8bc12eb0-b451-42c6-a754-247e63f3f6d7.png)

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by ShaneLimJiXuan** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
The diagrams look great! Thanks for the hard work guys. I shall close this issue.
