### ISSUE TITLE
03/10/2022 - 03/10/2022 2.5.2 Update Gantt Chart

### ISSUE THREAD

**Issue by ShaneLimJiXuan** [afifazfar07/ict2201-p1-8#96]
Start date: 03/10/2022
Estimated completion date: 03/10/2022

Completed date: 03/10/2022

Overall view of Gantt chart diagram

![Image](https://user-images.githubusercontent.com/90232201/198301662-193a5a79-b013-4f5f-92fa-862412166b7b.png)

Focused view of Gantt chart diagram part 1

![Image](https://user-images.githubusercontent.com/90232201/198302096-59c8f80d-a233-4886-bc78-a53266492992.png)

Gantt Chart Diagram Focused part 2

![Image](https://user-images.githubusercontent.com/90232201/198302208-29f6ec0c-a040-4480-8c03-4359a0552c86.png)

Gantt chart diagram Focused part 3

![Image](https://user-images.githubusercontent.com/90232201/198302408-27a857be-0130-413f-8c8d-11250800201b.png)

Gantt Chart Diagram Focused part 4
![Image](https://user-images.githubusercontent.com/90232201/198302501-96493887-8312-4645-aac0-ad3a71673ef3.png)

**Comment by ShaneLimJiXuan** [comment]
Look great to me

**Comment by 2102596sit** [comment]
Looks good to me

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
The Gantt chart is accurate on our work progress. Looks good to me! Thanks for the hard work guys. I shall close this issue.
