### ISSUE TITLE
06/10/2022 - 07/10/2022 2.1.3.5 Updated Use Case Descriptions

### ISSUE THREAD

**Issue by afifazfar07** [afifazfar07/ict2201-p1-8#97]
Start date: 06/10/2022
Estimated completion date: 07/10/2022

Completed date: 07/10/2022

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5b59dad7-7fff-a90d-cd94-56d00a48ff74"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-1 | Number of transactions: 4
-- | -- | --
Use Case Name: | Create account
Description: | Create user account for Manager and Staff.
Primary Actor: | Administrator
Preconditions: | User information such as names and roles in organisation.
Postconditions: | Main: User is created. System updates the Database.2a. If the same username already exists in the Database, user not created.E-mail sent.6a. E-mail was not sent.
Main Success Scenarios: | Administrator input username, e-mail address, phone number, gender, home address, the role of manager, ferry captain or crewmate.Administrator submits input.System prompts Administrator to confirm his/her input.Administrator accepts confirmation.System generates and set randomized passwords for the users.System registers new user successfully in Database.System display that a new user has been created.System send e-mail with system generated password with username to new user.
Alternative Scenarios: | 2a. Username already exist.2a1. System prompts the administrator to enter new username.
Priority | Medium

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-1fc16bf7-7fff-404b-f333-ce534ce702c8"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-2 | Number of transactions: 5
-- | -- | --
Use Case Name: | Assign job to staff
Description: | Assign job based on manpower availability and staff preference to staff.
Primary Actor: | Manager
Preconditions: | Manager is logged in. Job must be available. Staff must be registered in Database.
Postconditions: | Main: Confirmation e-mail sent. System updates in the Database.
Main Success Scenarios: | Manager selects date for route, timeslot and date.System display staff preference for selected route, timeslot and date.Manager submits input.System prompts Manager to confirm his/her input.Manager accepts confirmation.System updates the Database.System displays updated planning page.Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 6a. System fails to update Database.6a1. System gives a message “Update Fail, Try Aagin"6a2. Staff can choose to retry or quit screen.
Priority | High

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-c73c0acc-7fff-c9f6-4de6-a5ab588806af"><br /><br /><br /><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-3 | Number of transactions: 3
-- | -- | --
Use Case Name: | Add preference
Description: | Staff can add their job preference one week before allocation.
Primary Actor: | Staff
Preconditions: | Staff is logged in. Staff must be registered in Database.
Postconditions: | Main: Confirmation e-mail is sent to the staff. System updates in the Database.
Main Success Scenarios: | Staff selects date, route and time.Staff presses save.System updates Database.System display updated current preference for the week.Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 3a. System fails to update Database.3a1. System gives a message “Update Fail, Try Aagin3a2. Staff can choose to retry or quit screen.
Priority | High

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-57eabe53-7fff-396e-f847-8c27843039b1"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-4 | Number of transactions: 5
-- | -- | --
Use Case Name: | Edits preference
Description: | Staff can edit their job preference one week before allocation.
Primary Actor: | Staff
Preconditions: | Staff is logged in. Staff must be registered in Database. Existing preferences were made.
Postconditions: | Main: Confirmation e-mail is sent to the staff. System updates in the Database.
Main Success Scenarios: | Staff select dates with existing preference.System displays existing preferences.Staff presses the edit button.System display list of all available routes and time for selected date.Staff selects route and time for selected date.Staff presses save.System updates DatabaseSystem display updated current preference for the week.Confirmation e-mail is sent to the Staff e-mail mailbox.
Alternative Scenarios: | 7a. System fails to update Database.7a1. System gives a message “Update Fail, Try Aagin"7a2. Staff can choose to retry or quit screen.
Priority | High

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-722df39d-7fff-713c-f6f0-20725977ac97"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-5 | Number of transactions: 4
-- | -- | --
Use Case Name: | Removes preference
Description: | Staff can remove preference one week before allocation
Primary Actor: | Staff
Preconditions: | Staff is logged in. Staff must be registered in Database. Existing preferences were made.
Postconditions: | Main: Confirmation e-mail is sent to the staff. System updates in the Database.
Main Success Scenarios: | Staff select date with existing preference.System displays existing preference.Staff selects route and time for removal.Staff presses removeSystem updates DatabaseSystem display updated current preference for the week.Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 5a. System fails to update Database.5a1. System gives a message “Update Fail, Try Aagin"5a2. Staff can choose to retry or quit screen.
Priority | High

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-d41d9111-7fff-ab0e-e8ad-c8f2b0f9d498"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-6 | Number of transactions: 5
-- | -- | --
Use Case Name: | Reject job assignment
Description: | Staff rejects the job assigned to them by the manager.
Primary Actor: | Staff
Preconditions: | Staff is logged in. Manager has assigned staff to a job. Staff discussed with manager about reason for rejecting.
Postconditions: | Main: Database system has been updated. E-mail confirmation sent.
Main Success Scenarios: | System display dates and jobs assigned to staff.Staff selects date to reject.System displays jobs for the date.Staff selects jobs to reject.Staff presses reject.Staff input reason for rejecting the job.Staff submits their input.System updates Database.System displays updated job assignment.Confirmation e-mail sent to Manager and Staff e-mail mailbox.
Alternative Scenarios: | 8a. System fails to update Database.8a1. System gives a message “Update Fail, Try Again"8a2. Staff can choose to retry or quit screen.
Priority | Medium

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-1562f459-7fff-e74a-a17b-cb15af2d3eb7"><br /><br /><br /><br /><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-7 | Number of transactions: 5
-- | -- | --
Use Case Name: | Change account password
Description: | Staff change password for their account. Password is set to expire every 90 days.
Primary Actor: | Staff
Preconditions: | Staff knows current password. Staff password reaches password expiry date then system prompts for password change.
Postconditions: | Main: Confirmation e-mail sent.
Main Success Scenarios: | Staff goes to change password page.Staff input current ID and password.System validates entered password with Database-stored password.System prompts staff to enter new password.Staff input new password.System validates new password.System updates Database.System displays that password has been change.Confirmation e-mail sent to Staff e-mail mailbox.
Alternative Scenarios: | 3a. Entered password is incorrect.3a1. Staff can choose to re-enter password or quit screen.6a. New password same as old password.6a1. System prompts user to enter another password.
Priority | Low

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-1b323634-7fff-0c95-8b29-53ac7eea2529"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-8 | Number of transactions: 4
-- | -- | --
Use Case Name: | Delete account.
Description: | Delete user account for Manager and Staff.
Primary Actor: | Administrator
Preconditions: | User leaves organisation
Postconditions: | Main: User is deleted. System updates the Database.
Main Success Scenarios: | 1.  Administrator selects delete user2.  Administrator input username3.  Administrator submits input.4.  System prompts Administrator to confirm his/her input.5.  Administrator accepts confirmation.7.  System removes user successfully from Database.8.  System display that a user has been removed.9.  System send e-mail notification that a user has been deleted to the administrator
Alternative Scenarios: | 2a. Username does not exist.2a1. System prompts the administrator that the username does not exist.
Priority | Medium

</div></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-8719ad9a-7fff-61c5-a197-185ec265cfe2"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC-9 | Number of transactions: 2
-- | -- | --
Use Case Name: | Validate overall workload for the month
Description: | Staff valid overall workload for the month if there are discrepancy report to manager
Primary Actor: | Staff
Preconditions: | Workload is updated to the end of month.
Postconditions: | Main: Number of hours is correct
Main Success Scenarios: | System display workload for the monthStaff cross checks if workload amount is correctNumber of hours is correct
Alternative Scenarios: | 3a. Number of hours is incorrect3a1. Staff reports to manager to about discrepancy in work hours.
Priority | Low

</div><br /></b>
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-31eaffcf-7fff-78ec-5797-232c07553390"><div dir="ltr" style="margin-left:-5.75pt;" align="left">

Use Case ID: | UC10 | Number of transactions: 5
-- | -- | --
Use Case Name: | Edit Job Allocated to Staff
Description: | Edit existing job based on manpower availability and staff preference to staff.
Primary Actor: | Manager
Preconditions: | Manager is logged in. Job must be available. Staff must be registered in Database.
Postconditions: | Main: Confirmation e-mail sent. System updates in the Database.
Main Success Scenarios: | Manager selects pre-existing jobs allocation.System displays current job allocation and staffs' preferenceManager submits input.System prompts Manager to confirm his/her input.Manager accepts confirmation.System updates the Database.System displays updated planning page.Confirmation e-mail is sent to Staff e-mail mailbox.
Alternative Scenarios: | 6a. System fails to update Database.6a1. System gives a message “Update Fail, Try Again"6a2. Staff can choose to retry or quit screen.
Priority | High

</div><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="width:100px;display:inline-block;position:relative;"></span></span></p></b><br class="Apple-interchange-newline">
</body>
</html>

**Comment by ShaneLimJiXuan** [comment]
Looks good to me

**Comment by afifazfar07** [comment]
Looks good to me

**Comment by 2102596sit** [comment]
Looks great to me.

**Comment by S0meDev99** [comment]
The Use Case Descriptions looks good to me. I shall close this issue.
