### ISSUE TITLE
15/11/2022 - 19/11/2022 3.3 White Box Testing

### ISSUE THREAD

**Issue by 2102596sit** [afifazfar07/ict2201-p1-8#98]
Start date: 15/11/2022
Expected completion date: 19/11/2022

Drafted pseudocode , control flow graph with Cyclomatic Complexity and linearly independent paths 
Completed on 15/11/2022

![Image](https://user-images.githubusercontent.com/90232201/200352963-230b22f5-e3a9-4f43-be3c-38ec64394d78.png)

**Comment by afifazfar07** [comment]
LGTM

**Comment by ShaneLimJiXuan** [comment]
LGTM

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by 2102596sit** [comment]
The new iteration of pseudocode, a control flow graph with Cyclomatic Complexity and, linearly independent paths. With a better representation of the flow.

updated on 16/11/2022


![Image](https://user-images.githubusercontent.com/90232201/201727260-d969ef1e-a042-40fd-8b27-77b4d7e360cd.png)

**Comment by ShaneLimJiXuan** [comment]
LGTM

**Comment by afifazfar07** [comment]
looks good to me!

**Comment by S0meDev99** [comment]
LGTM!

Also have the Conditional Coverage and Test Case tables done.


![Image](https://user-images.githubusercontent.com/90775954/201727717-b0d431cf-fb54-4e77-b003-3651ad5235ff.png)

**Comment by afifazfar07** [comment]
Thanks! It looks good to me!

**Comment by 2102596sit** [comment]
Thanks, alford, LGTM!

**Comment by ShaneLimJiXuan** [comment]
Looks great!

**Comment by 2102596sit** [comment]
Revised control flow graph with Cyclomatic Complexity and, linearly independent paths. 
Fixed error by removing 2 additional nodes on p2 and p3  
p4 decision node is 19, not 20. The alternative node is 20, not 23.

edited on 18/11/2022



![Image](https://user-images.githubusercontent.com/90232201/202912473-491760ad-2366-43ab-9ed1-2480cc5755c9.png)

**Comment by ShaneLimJiXuan** [comment]
lgtm

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
The changes looks good to me!

**Comment by 2102596sit** [comment]
2nd Revision on control flow graph with Cyclomatic Complexity and, linearly independent paths.
Simplified CFG and rewrote test cases.

edited on 19/11/2022

**CFG with cyclomatic complexity**


![Image](https://user-images.githubusercontent.com/90232201/203771557-c0f8f361-e4aa-4c1b-9157-853b8b62c6fb.png)



**Test Cases**

![Image](https://user-images.githubusercontent.com/90232201/203374025-1b6a9e59-2dcf-4112-9ead-2d5ba81b9519.png)

![Image](https://user-images.githubusercontent.com/90232201/203374253-4b2cc5c4-f228-470c-8e0c-b1b713f4fc21.png)

**Comment by ShaneLimJiXuan** [comment]
lgtm

**Comment by S0meDev99** [comment]
Looks good to me!

**Comment by afifazfar07** [comment]
Looks good to me!

**Comment by ShaneLimJiXuan** [comment]
LGTM!

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
