### ISSUE TITLE
08/11/2022 - 08/11/2022 3.6.1 Update Gantt chart diagram

### ISSUE THREAD

**Issue by 2102596sit** [afifazfar07/ict2201-p1-8#99]
Overview of Gantt Chart Diagram
Updated as of 08/11/2022
![Image](https://user-images.githubusercontent.com/90232201/203763589-608fa8f4-a64a-43ee-b89b-59c2bf057920.png)

Focused view of Gantt Chart Diagram

![Image](https://user-images.githubusercontent.com/90232201/203764151-e62a7c76-c378-40c2-bf0a-c2a29945b5cf.png)

![Image](https://user-images.githubusercontent.com/90232201/203764277-6392ea87-514e-47ed-8315-c1c4899bc696.png)

![Image](https://user-images.githubusercontent.com/90232201/203764355-ee929176-b5fd-4edb-af78-9e2d1ab6ed6f.png)

![Image](https://user-images.githubusercontent.com/90232201/203764418-dbe7b5ff-bfe5-4946-b638-13860c1aebff.png)

**Comment by afifazfar07** [comment]
LGTM!

**Comment by ShaneLimJiXuan** [comment]
LGTM!

**Comment by 2102596sit** [comment]
Looks good to me!

**Comment by S0meDev99** [comment]
Looks good to me, I'll be closing this issue on the board. Good job guys!
